---
name: Build LaTeX document
on:
  push:

jobs:
  Upload-Word-Doc:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2
      - name: Upload a Word Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: incident-response-plan-template.docx
          path: incident-response-plan-template/incident-response-plan-template.docx
  Build-LaTeX-Doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        main_file:
          ["installation-guide-OSS", "usage-guide-OSS", "best-practices"]
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2
      - name: Compile LaTeX Doc
        id: compile-doc
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd ${{ matrix.main_file }}
            latexmk -pdf -file-line-error -halt-on-error \
            -interaction=nonstopmode main.tex
            makeglossaries main
            latexmk -pdf -file-line-error -halt-on-error \
            -interaction=nonstopmode main.tex
            makeglossaries main
            latexmk -pdf -file-line-error -halt-on-error \
            -interaction=nonstopmode main.tex
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.main_file }}.pdf
          path: ${{ matrix.main_file }}/main.pdf
  publish:
    runs-on: ubuntu-latest
    needs: ["Build-LaTeX-Doc", "Upload-Word-Doc"]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: etc/usr/artifacts/
      - name: Rename files
        run: |
          find etc/usr/artifacts/ -type f -name "main.pdf" -printf "/%P\n" \
          | while read -r FILE ; do DIR=$(dirname "$FILE" ); \
          mv etc/usr/artifacts/"$FILE" etc/usr/artifacts/"$DIR""$DIR";done
      - name: Check for files
        run: ls -la etc/usr/artifacts/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            etc/usr/artifacts/*/*.docx
            etc/usr/artifacts/*/*.pdf
