name: Build LaTeX document
on:
  push:
    branches-ignore: [main]

jobs:
  Build-LaTeX-Doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        main_file:
          [
            "installation-guide-OSS/main.tex",
            "usage-guide-OSS/main.tex",
            "best-practices/main.tex",
          ]
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2

      - name: Compile LaTeX Doc
        id: compile-doc
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.main_file }}
