name: Build LaTeX document
on:
  push:
    branches-ignore: [main]

jobs:
  Build-LaTeX-Doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        main_file:
          ["installation-guide-OSS", "usage-guide-OSS", "best-practices"]
    steps:
      - name: Set up Git Repository
        uses: actions/checkout@v2

      - name: Compile LaTeX Doc
        id: compile-doc
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          pre_compile: cd ${{ matrix.main_file }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: document
          path: ${{ matrix.main_file }}/main.pdf
